name: release

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repo
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SECRET_KEY }}
    - name: Push to Nelson Net
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add prod ssh://nelsonnetposting@angelo.gq/home/nelsonnetposting/nelsonnetposting-deployment/nelsonnetposting.git
        git push prod
