name: release

on: push

jobs:
  release-idk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: runs bash
        shell: bash
        run: |
          git clone git@github.com:Nelson-Net/nelsonnetposting.git
          cd ~/nelsonnetposting
          git init
          git add .
          git commit -m “pog.”
          git remote add origin ssh://nelsonnetposting@angelo.gq/home/nelsonnetposting/nelsonnetposting-deployment/nelsonnetposting.git
          git remote -v
          git push origin master
