name: release

on: push

jobs:
  release-idk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: runs bash
        shell: bash
        run: |
          git remote add pogger ssh://nelsonnetposting@angelo.gq/home/nelsonnetposting/nelsonnetposting-deployment/nelsonnetposting.git
          git push pogger main
