name: release

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Prepare ssh keys
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SECRET_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Checkout the Repo
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SECRET_KEY }}
        fetch-depth: 0
        ref: master
    - name: Push to Linode
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add prod ssh://nelsonnetposting@angelo.gq/home/nelsonnetposting/nelsonnetposting-deployment/nelsonnetposting.git
        git push prod
